server:
  port: 10451
  servlet:
    context-path: /
#spring:
#  datasource:
#    url: jdbc:mysql://8.141.159.53:3306/bank?useUnicode=true&characterEncoding=UTF-8
#    username: bank
#    password: BaNk1234
#    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  # R2dbcProperties
  r2dbc:
    url: r2dbcs:mysql://8.141.159.53:3306/zhixuan?sslMode=DISABLED&useUnicode=true&characterEncoding=UTF-8
    username: bank
    password: BaNk1234

